apiVersion: v1
kind: ConfigMap
metadata:
    name: config
data:
    config: |
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - {{.Values.ipRangeStart}}-{{.Values.ipRangeStop}}
